Feat/swarinfo 426: added swarmlist message handler
SwarmUS/HiveConnect pull request #26
Opened 2021-05-21 19:19 UTC by g-lesssard

Added handler for swarm list request with tests

2021-05-21 19:21 UTC, g-lesssard commented on cmake/propolis/common.cmake
> +        GIT_TAG        d8c5e8c6bd55e68ed94db566763458125fe6a080
TODO: change commit to master after merge

2021-05-28 00:40 UTC, xgroleau requested changes
Minor comment for logging a warning

2021-05-28 00:40 UTC, xgroleau commented on src/network/src/common/src/AbstractNetworkManager.cpp
> +        reinterpret_cast<bool (*)(const unsigned short&, const unsigned int&, void*)>(callback),
Is it necessary to cast or it'sd possible to match/edit the signature to avoid casting?

2021-05-28 00:40 UTC, xgroleau commented on src/message-handler/src/HiveConnectHiveMindMessageHandler.cpp
> +        uint8_t agentListLength = m_networkManager.getAgentList(agentList, NEIGHBORS_LIST_SIZE);
Use a uint16_t instead. Also what happens as if NEIGHBORS_LIST_SIZE is smaller than the agent list? Could it be possible to catch it and log a warning?

2021-05-29 17:08 UTC, xgroleau approved these changes
LGTM 👍

2021-05-29 17:09 UTC, merged